# This workflow will upload a Visual Studio Code Extension to the VS Code Marketplace

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Visual Studio Code Extension

on:
  release:
    types: [created]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install the dependencies
        run: npm i

      # - name: Install vsce
      #   run: npm i -g vsce

      # - name: Publish on VS Code marketplace
      #   run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Install ovsx
        run: npm i -g ovsx

      - name: Publish on Open VSX registry
        run: npx ovsx publish -p ${{ secrets.OVSX_PAT }}
